spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.example.learnKafka.* #adding the class to the trusted package (to avoid IllegalStateException)

server:
  port: 9060



