spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}

server:
  port: 9060


