spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/learnKafkaDB
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema:
        registry:
          url: "http://127.0.0.1:8081"


server:
  port: 9050

kafka.topic:
  user-random-topic: user-random-topic
  user-created-topic: user-created-topic

